name: Proposer un nouvel article
description: Création d’un article
title: "[Article] : "
labels: ["contenu"]
body:

  - type: input
    id: titre
    attributes:
      label: Titre
      description: Titre complet de l’article
      placeholder: "Ex: Coment ça marche une fantraduction ?"
    validations:
      required: true

  - type: textarea
    id: cover
    attributes:
      label: Image de couverture
      description: Ajoute ici l’image de couverture. Glisse l’image dans la zone, ou ajoute-la via le bouton pour ajouter une pièce jointe.
    validations:
      required: true

  - type: textarea
    id: excerpt
    attributes:
      label: Extrait
      description: Court résumé (1-2 phrases) qui servira de meta-description
      placeholder: "Un retour d’expérience sur…"
    validations:
      required: true

  - type: textarea
    id: contenu
    attributes:
      label: Contenu de l’article
      description: Rédige le texte complet (titres, paragraphes, images, etc.)
      placeholder: |
        # Introduction
        Texte ici...
    validations:
      required: true

