name: Proposer une nouveau visual novel en français
description: Ajouter une entrée sur la page découvrir
title: "[VNFR] : "
labels: ["contenu"]
projects: ["Site web contenu"]
body:

  - type: markdown
    attributes:
     value: |
       Merci de remplir ce formulaire pour proposer une nouvelle entrée de visual novel en français sur la page [Découvrir](https://dreamtrad.com/decouvrir). Plusieurs VN disponibles en français sont déjà listés sur la page, mais si on fait une [recherche vndb](https://vndb.org/v?q=&ch=&f=2gfr&s=26w), il y a plus d’un millier de VN disponible en français. Libre à vous de proposer le VN que vous voulez. Et si vous estimez qu’une fiche actuelle n’est pas complète, ou que le résumé ne fait pas honneur à l’œuvre, n’hésitez pas à proposer une modification.

       Pour inclure les jeux qui ne sont pas sur vndb, donc qui ne sont pas considérés comme des visual novels par vndb. Ça sera au cas par cas si le jeu peut être ajouté ou non. Suivant si c’est lié à une série de VN (ZTD pour Zero Escape), ou quand on reste proche du format VN (GNOSIA), ça peut le faire.

  - type: input
    id: titre
    attributes:
      label: Titre
      description: Titre complet du visual novel
      placeholder: "Titre"
    validations:
      required: true

  - type: checkboxes
    id: genre
    attributes:
      label: Genres
      description: Coche un ou plusieurs genres
      options:
        - label: comédie
        - label: drame
        - label: fantasy
        - label: horreur
        - label: gameplay
        - label: mystère
        - label: romance
        - label: science-fiction
        - label: tranche de vie

  - type: dropdown
    id: duree
    attributes:
      label: Durée
      description: Temps moyen du visual novel
      options:
        - "moins de 1h"
        - "1h-5h"
        - "5h-10h"
        - "10h-20h"
        - "20h-30h"
        - "30h-40h"
        - "40h-50h"
        - "50h-80h"
        - "plus de 80h"

  - type: checkboxes
    id: plateforme
    attributes:
      label: Plateformes
      description: Plateformes où le français est disponible
      options:
        - label: pc
        - label: psvita
        - label: ps4
        - label: switch
        - label: android
        - label: ios

  - type: textarea
    id: lien_jeu
    attributes:
      label: Liens
      description: Lien vndb + Liens pour le VN où le français est disponible officiellemen ou par patch (un lien par ligne, préfixé par `-`)
      placeholder: |
        - https://vndb.org/vxxxx
        - https://store.steampowered.com/app/xxxxx/

  - type: textarea
    id: patch_fr
    attributes:
      label: Patch FR
      description: Liens des patchs FR (un lien par ligne, préfixé par `-`)
      placeholder: |
        - https://dreamtrad.com/...

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Résumé du VN, précisez la série et le numéro de l'épisode si besoin
      placeholder: "Description longue"

  - type: textarea
    id: ticket
    attributes:
      label: explication
      description: Si des points bloquent (manque le genre, champ pas clair, questions…), expliquez ici.
