name: Proposer un nouvel article
description: Création d’un article
title: "[Article] : "
labels: ["contenu"]
projects: ["Site web contenu"]
body:

  - type: markdown
    attributes:
     value: |
        Les articles doivent être un minimum en lien avec soit les visual novels traduits par l’équipe, soit sur les visual novel en général, soit sur le sujet de la traduction. Ça peut être une actualité, ou un dossier, un témoignage… Mais sentez-vous libre de proposer un article sur un sujet, juste le titre et l’explication de pourquoi cet article, et si on valide, pour pourrez rédiger l’article ensuite en modifiant l’issue.

  - type: textarea
    id: explication
    attributes:
      label: Explication
      description: Explique en quelques lignes le sujet de l’article, et pourquoi tu veux écrire dessus. Ou pose tes questions si tu as besoin d’aide.

  - type: input
    id: titre
    attributes:
      label: Titre
      description: Titre complet de l’article
      placeholder: "Ex: Coment ça marche une fantraduction ?"
    validations:
      required: true

  - type: textarea
    id: cover
    attributes:
      label: Image de couverture
      description: Ajoute ici l’image de couverture. Glisse l’image dans la zone, ou ajoute-la via le bouton pour ajouter une pièce jointe.

  - type: textarea
    id: excerpt
    attributes:
      label: Extrait
      description: Court résumé (1-2 phrases) qui servira de meta-description
      placeholder: "Un retour d’expérience sur…"

  - type: textarea
    id: contenu
    attributes:
      label: Contenu de l’article
      description: Rédige le texte complet (titres, paragraphes, images, etc.)
      placeholder: |
        # Introduction
        Texte ici...

