name: Proposer une nouvelle entrée JSON
description: Ajouter une nouvelle entrée au fichier JSON du projet
title: "[Entrée] : "
labels: ["nouvelle entrée"]
body:
  - type: input
    id: id
    attributes:
      label: Identifiant
      description: ID unique de l'entrée (ex: danganronpa_2)
      placeholder: "id_jeu"
    validations:
      required: true

  - type: input
    id: titre
    attributes:
      label: Titre
      description: Titre complet du jeu/visual novel
      placeholder: "Titre du jeu"
    validations:
      required: true

  - type: input
    id: image
    attributes:
      label: Image
      description: Chemin vers l’image
      placeholder: "assets/poster/xxx.webp"

  - type: checkboxes
    id: genre
    attributes:
      label: Genres
      description: Coche un ou plusieurs genres
      options:
        - label: enquête
        - label: gameplay
        - label: romance
        - label: horreur
        - label: science-fiction
        - label: drame

  - type: dropdown
    id: duree
    attributes:
      label: Durée
      description: Temps moyen de jeu
      options:
        - "Moins de 10h"
        - "10h-20h"
        - "20h-30h"
        - "30h-40h"
        - "40h+"

  - type: input
    id: note_vndb
    attributes:
      label: Note VNDB
      placeholder: "8,10"

  - type: input
    id: popularite_vndb
    attributes:
      label: Popularité VNDB
      placeholder: "10"

  - type: checkboxes
    id: plateforme
    attributes:
      label: Plateformes
      description: Sélectionne les plateformes disponibles
      options:
        - label: pc
        - label: psvita
        - label: ps4
        - label: switch
        - label: android
        - label: ios

  - type: textarea
    id: lien_jeu
    attributes:
      label: Liens
      description: Liens VNDB, Steam, etc. (format JSON array)
      placeholder: |
        [
          "https://vndb.org/vxxxx",
          "https://store.steampowered.com/app/xxxxx/"
        ]

  - type: textarea
    id: patch_fr
    attributes:
      label: Patch FR
      description: Lien(s) vers patch(s) FR (format JSON array)
      placeholder: |
        ["fr:https://equipemirai.com/..."]

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Résumé du jeu
      placeholder: "Description longue"
