name: Proposer une nouveau visual novel en français
description: Ajouter une entrée sur la page découvrir
title: "[VNFR] : "
labels: ["nouvelle entrée"]
body:

  - type: input
    id: titre
    attributes:
      label: Titre
      description: Titre complet du visual novel
      placeholder: "Titre du jeu"
    validations:
      required: true

  - type: checkboxes
    id: genre
    attributes:
      label: Genres
      description: Coche un ou plusieurs genres
      options:
        - label: enquête
        - label: gameplay
        - label: romance
        - label: horreur
        - label: science-fiction
        - label: drame

  - type: dropdown
    id: duree
    attributes:
      label: Durée
      description: Temps moyen de jeu
      options:
        - "Moins de 10h"
        - "10h-20h"
        - "20h-30h"
        - "30h-40h"
        - "40h+"

  - type: input
    id: note_vndb
    attributes:
      label: Note VNDB
      placeholder: "8,10"

  - type: input
    id: popularite_vndb
    attributes:
      label: Rang de popularité VNDB
      placeholder: "14"

  - type: checkboxes
    id: plateforme
    attributes:
      label: Plateformes
      description: Plateformes où le français est disponible
      options:
        - label: pc
        - label: psvita
        - label: ps4
        - label: switch
        - label: android
        - label: ios

  - type: textarea
    id: lien_jeu
    attributes:
      label: Liens
      description: Fournis une liste en markdown (un lien par ligne, préfixé par `-`)
      placeholder: |
        - https://vndb.org/vxxxx
        - https://store.steampowered.com/app/xxxxx/

  - type: textarea
    id: patch_fr
    attributes:
      label: Patch FR
      description: Fournis une liste en markdown (un lien par ligne, préfixé par `-`)
      placeholder: |
        - https://dreamtrad.com/...

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Résumé du jeu
      placeholder: "Description longue"


  - type: textarea
    id: ticket
    attributes:
      label: explication
      description: Si des points bloquent (manque le gerne, champ pas clair…), explique ici
