name: Proposer une nouveau visual novel en français
description: Ajouter une entrée sur la page découvrir
title: "[VNFR] : "
labels: ["nouvelle entrée"]
body:

  - type: input
    id: titre
    attributes:
      label: Titre
      description: Titre complet du visual novel
      placeholder: "Titre du jeu"
    validations:
      required: true

  - type: checkboxes
    id: genre
    attributes:
      label: Genres
      description: Coche un ou plusieurs genres
      options:
        - label: comédie
        - label: drame
        - label: fantasy
        - label: horreur
        - label: gameplay
        - label: mystère
        - label: romance
        - label: science-fiction
        - label: tranche de vie

  - type: dropdown
    id: duree
    attributes:
      label: Durée
      description: Temps moyen de jeu
      options:
        - "moins de 1h"
        - "1h-5h"
        - "5h-10h"
        - "10h-20h"
        - "20h-30h"
        - "30h-40h"
        - "40h-50h"
        - "50h-80h"
        - "plus de 80h"

  - type: checkboxes
    id: plateforme
    attributes:
      label: Plateformes
      description: Plateformes où le français est disponible
      options:
        - label: pc
        - label: psvita
        - label: ps4
        - label: switch
        - label: android
        - label: ios

  - type: textarea
    id: lien_jeu
    attributes:
      label: Liens
      description: Lien vndb + Liens pour le VN où le français est disponible (un lien par ligne, préfixé par `-`)
      placeholder: |
        - https://vndb.org/vxxxx
        - https://store.steampowered.com/app/xxxxx/

  - type: textarea
    id: patch_fr
    attributes:
      label: Patch FR
      description: Liens des patchs FR (un lien par ligne, préfixé par `-`)
      placeholder: |
        - https://dreamtrad.com/...

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Résumé du VN, précisez la série et le numéro de l'épisode si besoin
      placeholder: "Description longue"


  - type: textarea
    id: ticket
    attributes:
      label: explication
      description: Si des points bloquent (manque le genre, champ pas clair…), expliquez ici
